#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Copyright 2016 JeaRRo <jean.navarro@laposte.net>
#  http://wiki.openstreetmap.org/wiki/User:JeaRRo
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
# dictionnaire des départements
#
#     Ce fichier est généré par le programme param_gen.py après que le fichier special.py est été complété manuellement.
#
dic_dep = {'01' :{'text': "de l'Ain", 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Ain", 'name': 'Ain', 'code': '01'},
'02' :{'text': "de l'Aisne", 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Aisne_(nord)", "/wiki/Liste_des_monuments_historiques_de_l'Aisne_(sud)"], 'name': 'Aisne', 'code': '02'},
'03' :{'text': "de l'Allier", 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Allier_(A-H)", "/wiki/Liste_des_monuments_historiques_de_l'Allier_(I-Z)"], 'name': 'Allier', 'code': '03'},
'04' :{'text': 'des Alpes-de-Haute-Provence', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Alpes-de-Haute-Provence', 'name': 'Alpes-de-Haute-Provence', 'code': '04'},
'05' :{'text': 'des Hautes-Alpes', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Hautes-Alpes', 'name': 'Hautes-Alpes', 'code': '05'},
'06' :{'text': 'des Alpes-Maritimes', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Alpes-Maritimes', 'name': 'Alpes-Maritimes', 'code': '06'},
'07' :{'text': "de l'Ardèche", 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Ardèche", 'name': 'Ardèche', 'code': '07'},
'08' :{'text': 'des Ardennes', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Ardennes', 'name': 'Ardennes', 'code': '08'},
'09' :{'text': "de l'Ariège", 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Ariège", 'name': 'Ariège', 'code': '09'},
'10' :{'text': "de l'Aube", 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Aube", 'name': 'Aube', 'code': '10'},
'11' :{'text': "de l'Aude", 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Aude", 'name': 'Aude', 'code': '11'},
'12' :{'text': "de l'Aveyron", 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Aveyron", 'name': 'Aveyron', 'code': '12'},
'13' :{'text': 'des Bouches-du-Rhône', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Bouches-du-Rhône', 'name': 'Bouches-du-Rhône', 'code': '13'},
'14' :{'text': 'du Calvados', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Bayeux", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Caen", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Lisieux", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Vire"], 'name': 'Calvados', 'code': '14'},
'15' :{'text': 'du Cantal', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Cantal', 'name': 'Cantal', 'code': '15'},
'16' :{'text': 'de la Charente', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Charente', 'name': 'Charente', 'code': '16'},
'17' :{'text': 'de la Charente-Maritime', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Charente-Maritime_(A-N)', '/wiki/Liste_des_monuments_historiques_de_la_Charente-Maritime_(O-Z)'], 'name': 'Charente-Maritime', 'code': '17'},
'18' :{'text': 'du Cher', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Cher', 'name': 'Cher', 'code': '18'},
'19' :{'text': 'de la Corrèze', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Corrèze', 'name': 'Corrèze', 'code': '19'},
'2A' :{'text': 'de la Corse-du-Sud', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Corse-du-Sud', 'name': 'Corse-du-Sud', 'code': '2A'},
'2B' :{'text': 'de la Haute-Corse', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Haute-Corse', 'name': 'Haute-Corse', 'code': '2B'},
'21' :{'text': "de la Côte-d'Or", 'url_d': ["/wiki/Liste_des_monuments_historiques_de_la_Côte-d'Or_(A-L)", "/wiki/Liste_des_monuments_historiques_de_la_Côte-d'Or_(M-Z)"], 'name': "Côte-d'Or", 'code': '21'},
'22' :{'text': "des Côtes-d'Armor", 'url_d': ["/wiki/Liste_des_monuments_historiques_des_Côtes-d'Armor_(A-O)", "/wiki/Liste_des_monuments_historiques_des_Côtes-d'Armor_(P-Z)"], 'name': "Côtes-d'Armor", 'code': '22'},
'23' :{'text': 'de la Creuse', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Creuse', 'name': 'Creuse', 'code': '23'},
'24' :{'text': 'de la Dordogne', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Bergerac", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Nontron", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Périgueux", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Sarlat-la-Canéda"], 'name': 'Dordogne', 'code': '24'},
'25' :{'text': 'du Doubs', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Doubs', 'name': 'Doubs', 'code': '25'},
'26' :{'text': 'de la Drôme', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Drôme', 'name': 'Drôme', 'code': '26'},
'27' :{'text': "de l'Eure", 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Eure_(A-I)", "/wiki/Liste_des_monuments_historiques_de_l'Eure_(J-Z)"], 'name': 'Eure', 'code': '27'},
'28' :{'text': "d'Eure-et-Loir", 'url_d': "/wiki/Liste_des_monuments_historiques_d'Eure-et-Loir", 'name': 'Eure-et-Loir', 'code': '28'},
'29' :{'text': 'du Finistère', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Finistère_(A-O)', '/wiki/Liste_des_monuments_historiques_du_Finistère_(P-Z)'], 'name': 'Finistère', 'code': '29'},
'30' :{'text': 'du Gard', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Gard', 'name': 'Gard', 'code': '30'},
'31' :{'text': 'de la Haute-Garonne', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Haute_Garonne_(A-L)', '/wiki/Liste_des_monuments_historiques_de_la_Haute_Garonne_(M-Z)'], 'name': 'Haute-Garonne', 'code': '31'},
'32' :{'text': 'du Gers', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Gers', 'name': 'Gers', 'code': '32'},
'33' :{'text': 'de la Gironde', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Arcachon", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Blaye", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Bordeaux", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Langon", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Lesparre-Médoc", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Libourne"], 'name': 'Gironde', 'code': '33'},
'34' :{'text': "de l'Hérault", 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Eure_(A-I)", "/wiki/Liste_des_monuments_historiques_de_l'Eure_(J-Z)"], 'name': 'Hérault', 'code': '34'},
'35' :{'text': "d'Ille-et-Vilaine", 'url_d': "/wiki/Liste_des_monuments_historiques_d'Ille-et-Vilaine", 'name': 'Ille-et-Vilaine', 'code': '35'},
'36' :{'text': "de l'Indre", 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Indre", 'name': 'Indre', 'code': '36'},
'37' :{'text': "d'Indre-et-Loire", 'url_d': ["/wiki/Liste_des_monuments_historiques_d'Indre-et-Loire_(A-J)", "/wiki/Liste_des_monuments_historiques_d'Indre-et-Loire_(K-Z)"], 'name': 'Indre-et-Loire', 'code': '37'},
'38' :{'text': "de l'Isère", 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Isère", 'name': 'Isère', 'code': '38'},
'39' :{'text': 'du département du Jura', 'url_d': '/wiki/Liste_des_monuments_historiques_du_département_du_Jura', 'name': 'Jura', 'code': '39'},
'40' :{'text': 'des Landes', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Landes', 'name': 'Landes', 'code': '40'},
'41' :{'text': 'de Loir-et-Cher', 'url_d': '/wiki/Liste_des_monuments_historiques_de_Loir-et-Cher', 'name': 'Loir-et-Cher', 'code': '41'},
'42' :{'text': 'de la Loire', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Loire', 'name': 'Loire', 'code': '42'},
'43' :{'text': 'de la Haute-Loire', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Haute_Loire_(ouest)', '/wiki/Liste_des_monuments_historiques_de_la_Haute_Loire_(est)'], 'name': 'Haute-Loire', 'code': '43'},
'44' :{'text': 'de la Loire-Atlantique', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Loire-Atlantique', 'name': 'Loire-Atlantique', 'code': '44'},
'45' :{'text': 'du Loiret', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Loiret', 'name': 'Loiret', 'code': '45'},
'46' :{'text': 'du Lot', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Lot_(A-K)', '/wiki/Liste_des_monuments_historiques_du_Lot_(L-Z)'], 'name': 'Lot', 'code': '46'},
'47' :{'text': 'de Lot-et-Garonne', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Lot-et-Garonne_(A-L)', '/wiki/Liste_des_monuments_historiques_du_Lot-et-Garonne_(M-Z)'], 'name': 'Lot-et-Garonne', 'code': '47'},
'48' :{'text': 'de la Lozère', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Lozère', 'name': 'Lozère', 'code': '48'},
'49' :{'text': 'de Maine-et-Loire', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Maine-et-Loire_(nord)', '/wiki/Liste_des_monuments_historiques_du_Maine-et-Loire_(sud)'], 'name': 'Maine-et-Loire', 'code': '49'},
'50' :{'text': 'de la Manche', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Manche', 'name': 'Manche', 'code': '50'},
'51' :{'text': 'de la Marne', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Marne', 'name': 'Marne', 'code': '51'},
'52' :{'text': 'de la Haute-Marne', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Haute-Marne', 'name': 'Haute-Marne', 'code': '52'},
'53' :{'text': 'de la Mayenne', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Mayenne', 'name': 'Mayenne', 'code': '53'},
'54' :{'text': 'de Meurthe-et-Moselle', 'url_d': '/wiki/Liste_des_monuments_historiques_de_Meurthe-et-Moselle', 'name': 'Meurthe-et-Moselle', 'code': '54'},
'55' :{'text': 'de la Meuse', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Meuse', 'name': 'Meuse', 'code': '55'},
'56' :{'text': 'du Morbihan', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Lorient", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Pontivy", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Vannes"], 'name': 'Morbihan', 'code': '56'},
'57' :{'text': 'de la Moselle', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Moselle', 'name': 'Moselle', 'code': '57'},
'58' :{'text': 'de la Nièvre', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Nièvre', 'name': 'Nièvre', 'code': '58'},
'59' :{'text': 'du Nord', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Nord_(A-L)', '/wiki/Liste_des_monuments_historiques_du_Nord_(M-Z)'], 'name': 'Nord', 'code': '59'},
'60' :{'text': "de l'Oise", 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Oise_(ouest)", "/wiki/Liste_des_monuments_historiques_de_l'Oise_(est)"], 'name': 'Oise', 'code': '60'},
'61' :{'text': "de l'Orne", 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Orne", 'name': 'Orne', 'code': '61'},
'62' :{'text': 'du Pas-de-Calais', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Pas-de-Calais_(A-H)', '/wiki/Liste_des_monuments_historiques_du_Pas-de-Calais_(I-Z)'], 'name': 'Pas-de-Calais', 'code': '62'},
'63' :{'text': 'du Puy-de-Dôme', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Puy-de-Dôme_(A-L)', '/wiki/Liste_des_monuments_historiques_du_Puy-de-Dôme_(M-Z)'], 'name': 'Puy-de-Dôme', 'code': '63'},
'64' :{'text': 'des Pyrénées-Atlantiques', 'url_d': ['/wiki/Liste_des_monuments_historiques_des_Pyrénées-Atlantiques_(A-L)', '/wiki/Liste_des_monuments_historiques_des_Pyrénées-Atlantiques_(M-Z)'], 'name': 'Pyrénées-Atlantiques', 'code': '64'},
'65' :{'text': 'des Hautes-Pyrénées', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Hautes-Pyrénées', 'name': 'Hautes-Pyrénées', 'code': '65'},
'66' :{'text': 'des Pyrénées-Orientales', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Pyrénées-Orientales', 'name': 'Pyrénées-Orientales', 'code': '66'},
'67' :{'text': 'du Bas-Rhin', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Bas-Rhin_(A-L)', '/wiki/Liste_des_monuments_historiques_du_Bas-Rhin_(M-Z)'], 'name': 'Bas-Rhin', 'code': '67'},
'68' :{'text': 'du Haut-Rhin', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Haut-Rhin', 'name': 'Haut-Rhin', 'code': '68'},
'69' :{'text': 'du Rhône', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Rhône', '/wiki/Liste_des_monuments_historiques_de_la_Métropole_de_Lyon'], 'name': 'Rhône', 'code': '69'},
'70' :{'text': 'de la Haute-Saône', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Haute-Saône_(Vesoul_-_Gray)', '/wiki/Liste_des_monuments_historiques_de_la_Haute-Saône_(Lure_-_Héricourt)', '/wiki/Liste_des_monuments_historiques_de_la_Haute-Saône_(Luxeuil_-_Jussey)'], 'name': 'Haute-Saône', 'code': '70'},
'71' :{'text': 'de Saône-et-Loire', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Saône-et-Loire_(A-L)', '/wiki/Liste_des_monuments_historiques_de_la_Saône-et-Loire_(M-Z)'], 'name': 'Saône-et-Loire', 'code': '71'},
'72' :{'text': 'de la Sarthe', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Mamers", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_du_Mans", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_la_Flèche"], 'name': 'Sarthe', 'code': '72'},
'73' :{'text': 'de la Savoie', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Savoie', 'name': 'Savoie', 'code': '73'},
'74' :{'text': 'de la Haute-Savoie', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Haute-Savoie', 'name': 'Haute-Savoie', 'code': '74'},
'75' :{'text': 'de Paris', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_1er_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_2e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_3e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_4e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_5e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_6e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_7e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_8e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_9e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_10e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_11e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_12e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_13e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_14e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_15e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_16e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_17e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_18e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_19e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_20e_arrondissement_de_Paris'], 'name': 'Paris', 'code': '75'},
'76' :{'text': 'de la Seine-Maritime', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Dieppe", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_du_Havre", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Rouen"], 'name': 'Seine-Maritime', 'code': '76'},
'77' :{'text': 'de Seine-et-Marne', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Seine-Maritime_(ouest)', '/wiki/Liste_des_monuments_historiques_de_la_Seine-Maritime_(est)'], 'name': 'Seine-et-Marne', 'code': '77'},
'78' :{'text': 'des Yvelines', 'url_d': ['/wiki/Liste_des_monuments_historiques_des_Yvelines_(nord)', '/wiki/Liste_des_monuments_historiques_des_Yvelines_(sud)'], 'name': 'Yvelines', 'code': '78'},
'79' :{'text': 'des Deux-Sèvres', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Deux-Sèvres', 'name': 'Deux-Sèvres', 'code': '79'},
'80' :{'text': 'de la Somme', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Somme', 'name': 'Somme', 'code': '80'},
'81' :{'text': 'du Tarn', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Tarn', 'name': 'Tarn', 'code': '81'},
'82' :{'text': 'de Tarn-et-Garonne', 'url_d': '/wiki/Liste_des_monuments_historiques_de_Tarn-et-Garonne', 'name': 'Tarn-et-Garonne', 'code': '82'},
'83' :{'text': 'du Var', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Var', 'name': 'Var', 'code': '83'},
'84' :{'text': 'de Vaucluse', 'url_d': '/wiki/Liste_des_monuments_historiques_de_Vaucluse', 'name': 'Vaucluse', 'code': '84'},
'85' :{'text': 'de la Vendée', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Vendée', 'name': 'Vendée', 'code': '85'},
'86' :{'text': 'de la Vienne', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Vienne_(A-L)', '/wiki/Liste_des_monuments_historiques_de_la_Vienne_(M-Z)'], 'name': 'Vienne', 'code': '86'},
'87' :{'text': 'de la Haute-Vienne', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Haute-Vienne', 'name': 'Haute-Vienne', 'code': '87'},
'88' :{'text': 'des Vosges', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Vosges', 'name': 'Vosges', 'code': '88'},
'89' :{'text': "de l'Yonne", 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Yonne_(A-M)", "/wiki/Liste_des_monuments_historiques_de_l'Yonne_(N-Z)"], 'name': 'Yonne', 'code': '89'},
'90' :{'text': 'du Territoire de Belfort', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Territoire_de_Belfort', 'name': 'Territoire de Belfort', 'code': '90'},
'91' :{'text': "de l'Essonne", 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Essonne", 'name': 'Essonne', 'code': '91'},
'92' :{'text': 'des Hauts-de-Seine', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Hauts-de-Seine', 'name': 'Hauts-de-Seine', 'code': '92'},
'93' :{'text': 'de la Seine-Saint-Denis', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Seine-Saint-Denis', 'name': 'Seine-Saint-Denis', 'code': '93'},
'94' :{'text': 'du Val-de-Marne', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Val-de-Marne', 'name': 'Val-de-Marne', 'code': '94'},
'95' :{'text': "du Val-d'Oise", 'url_d': "/wiki/Liste_des_monuments_historiques_du_Val-d'Oise", 'name': "Val-d'Oise", 'code': '95'},
'971' :{'text': 'de la Guadeloupe', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Guadeloupe', 'name': 'Guadeloupe', 'code': '971'},
'972' :{'text': 'de la Martinique', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Martinique', 'name': 'Martinique', 'code': '972'},
'973' :{'text': 'de la Guyane', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Guyane', 'name': 'Guyane', 'code': '973'},
'974' :{'text': 'de La Réunion', 'url_d': '/wiki/Liste_des_monuments_historiques_de_La_Réunion', 'name': 'Réunion', 'code': '974'},
'975' :{'text': 'de Saint-Pierre-et-Miquelon', 'url_d': '/wiki/Liste_des_monuments_historiques_de_Saint-Pierre-et-Miquelon', 'name': 'Saint-Pierre-et-Miquelon', 'code': '975'},
}