dic_dep = {'01' :{'text': "de l'Ain", 'code': '01', 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Ain", 'name': 'Ain'},
'02' :{'text': "de l'Aisne", 'code': '02', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Aisne_(nord)", "/wiki/Liste_des_monuments_historiques_de_l'Aisne_(sud)"], 'name': 'Aisne'},
'03' :{'text': "de l'Allier", 'code': '03', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Allier_(A-H)", "/wiki/Liste_des_monuments_historiques_de_l'Allier_(I-Z)"], 'name': 'Allier'},
'04' :{'text': 'des Alpes-de-Haute-Provence', 'code': '04', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Alpes-de-Haute-Provence', 'name': 'Alpes-de-Haute-Provence'},
'05' :{'text': 'des Hautes-Alpes', 'code': '05', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Hautes-Alpes', 'name': 'Hautes-Alpes'},
'06' :{'text': 'des Alpes-Maritimes', 'code': '06', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Alpes-Maritimes', 'name': 'Alpes-Maritimes'},
'07' :{'text': "de l'Ardèche", 'code': '07', 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Ardèche", 'name': 'Ardèche'},
'08' :{'text': 'des Ardennes', 'code': '08', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Ardennes', 'name': 'Ardennes'},
'09' :{'text': "de l'Ariège", 'code': '09', 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Ariège", 'name': 'Ariège'},
'10' :{'text': "de l'Aube", 'code': '10', 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Aube", 'name': 'Aube'},
'11' :{'text': "de l'Aude", 'code': '11', 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Aude", 'name': 'Aude'},
'12' :{'text': "de l'Aveyron", 'code': '12', 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Aveyron", 'name': 'Aveyron'},
'13' :{'text': 'des Bouches-du-Rhône', 'code': '13', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Bouches-du-Rhône', 'name': 'Bouches-du-Rhône'},
'14' :{'text': 'du Calvados', 'code': '14', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Bayeux", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Caen", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Lisieux", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Vire"], 'name': 'Calvados'},
'15' :{'text': 'du Cantal', 'code': '15', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Cantal', 'name': 'Cantal'},
'16' :{'text': 'de la Charente', 'code': '16', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Charente', 'name': 'Charente'},
'17' :{'text': 'de la Charente-Maritime', 'code': '17', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Charente-Maritime_(A-N)', '/wiki/Liste_des_monuments_historiques_de_la_Charente-Maritime_(O-Z)'], 'name': 'Charente-Maritime'},
'18' :{'text': 'du Cher', 'code': '18', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Cher', 'name': 'Cher'},
'19' :{'text': 'de la Corrèze', 'code': '19', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Corrèze', 'name': 'Corrèze'},
'2A' :{'text': 'de la Corse-du-Sud', 'code': '2A', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Corse-du-Sud', 'name': 'Corse-du-Sud'},
'2B' :{'text': 'de la Haute-Corse', 'code': '2B', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Haute-Corse', 'name': 'Haute-Corse'},
'21' :{'text': "de la Côte-d'Or", 'code': '21', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_la_Côte-d'Or_(A-L)", "/wiki/Liste_des_monuments_historiques_de_la_Côte-d'Or_(M-Z)"], 'name': "Côte-d'Or"},
'22' :{'text': "des Côtes-d'Armor", 'code': '22', 'url_d': ["/wiki/Liste_des_monuments_historiques_des_Côtes-d'Armor_(A-O)", "/wiki/Liste_des_monuments_historiques_des_Côtes-d'Armor_(P-Z)"], 'name': "Côtes-d'Armor"},
'23' :{'text': 'de la Creuse', 'code': '23', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Creuse', 'name': 'Creuse'},
'24' :{'text': 'de la Dordogne', 'code': '24', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Bergerac", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Nontron", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Périgueux", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Sarlat-la-Canéda"], 'name': 'Dordogne'},
'25' :{'text': 'du Doubs', 'code': '25', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Doubs', 'name': 'Doubs'},
'26' :{'text': 'de la Drôme', 'code': '26', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Drôme', 'name': 'Drôme'},
'27' :{'text': "de l'Eure", 'code': '27', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Eure_(A-I)", "/wiki/Liste_des_monuments_historiques_de_l'Eure_(J-Z)"], 'name': 'Eure'},
'28' :{'text': "d'Eure-et-Loir", 'code': '28', 'url_d': "/wiki/Liste_des_monuments_historiques_d'Eure-et-Loir", 'name': 'Eure-et-Loir'},
'29' :{'text': 'du Finistère', 'code': '29', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Finistère_(A-O)', '/wiki/Liste_des_monuments_historiques_du_Finistère_(P-Z)'], 'name': 'Finistère'},
'30' :{'text': 'du Gard', 'code': '30', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Gard', 'name': 'Gard'},
'31' :{'text': 'de la Haute-Garonne', 'code': '31', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Haute_Garonne_(A-L)', '/wiki/Liste_des_monuments_historiques_de_la_Haute_Garonne_(M-Z)'], 'name': 'Haute-Garonne'},
'32' :{'text': 'du Gers', 'code': '32', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Gers', 'name': 'Gers'},
'33' :{'text': 'de la Gironde', 'code': '33', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Arcachon", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Blaye", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Bordeaux", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Langon", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Lesparre-Médoc", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Libourne"], 'name': 'Gironde'},
'34' :{'text': "de l'Hérault", 'code': '34', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Eure_(A-I)", "/wiki/Liste_des_monuments_historiques_de_l'Eure_(J-Z)"], 'name': 'Hérault'},
'35' :{'text': "d'Ille-et-Vilaine", 'code': '35', 'url_d': "/wiki/Liste_des_monuments_historiques_d'Ille-et-Vilaine", 'name': 'Ille-et-Vilaine'},
'36' :{'text': "de l'Indre", 'code': '36', 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Indre", 'name': 'Indre'},
'37' :{'text': "d'Indre-et-Loire", 'code': '37', 'url_d': ["/wiki/Liste_des_monuments_historiques_d'Indre-et-Loire_(A-J)", "/wiki/Liste_des_monuments_historiques_d'Indre-et-Loire_(K-Z)"], 'name': 'Indre-et-Loire'},
'38' :{'text': "de l'Isère", 'code': '38', 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Isère", 'name': 'Isère'},
'39' :{'text': 'du département du Jura', 'code': '39', 'url_d': '/wiki/Liste_des_monuments_historiques_du_département_du_Jura', 'name': 'Jura'},
'40' :{'text': 'des Landes', 'code': '40', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Landes', 'name': 'Landes'},
'41' :{'text': 'de Loir-et-Cher', 'code': '41', 'url_d': '/wiki/Liste_des_monuments_historiques_de_Loir-et-Cher', 'name': 'Loir-et-Cher'},
'42' :{'text': 'de la Loire', 'code': '42', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Loire', 'name': 'Loire'},
'43' :{'text': 'de la Haute-Loire', 'code': '43', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Haute_Loire_(ouest)', '/wiki/Liste_des_monuments_historiques_de_la_Haute_Loire_(est)'], 'name': 'Haute-Loire'},
'44' :{'text': 'de la Loire-Atlantique', 'code': '44', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Loire-Atlantique', 'name': 'Loire-Atlantique'},
'45' :{'text': 'du Loiret', 'code': '45', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Loiret', 'name': 'Loiret'},
'46' :{'text': 'du Lot', 'code': '46', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Lot_(A-K)', '/wiki/Liste_des_monuments_historiques_du_Lot_(L-Z)'], 'name': 'Lot'},
'47' :{'text': 'de Lot-et-Garonne', 'code': '47', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Lot-et-Garonne_(A-L)', '/wiki/Liste_des_monuments_historiques_du_Lot-et-Garonne_(M-Z)'], 'name': 'Lot-et-Garonne'},
'48' :{'text': 'de la Lozère', 'code': '48', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Lozère', 'name': 'Lozère'},
'49' :{'text': 'de Maine-et-Loire', 'code': '49', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Maine-et-Loire_(nord)', '/wiki/Liste_des_monuments_historiques_du_Maine-et-Loire_(sud)'], 'name': 'Maine-et-Loire'},
'50' :{'text': 'de la Manche', 'code': '50', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Manche', 'name': 'Manche'},
'51' :{'text': 'de la Marne', 'code': '51', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Marne', 'name': 'Marne'},
'52' :{'text': 'de la Haute-Marne', 'code': '52', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Haute-Marne', 'name': 'Haute-Marne'},
'53' :{'text': 'de la Mayenne', 'code': '53', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Mayenne', 'name': 'Mayenne'},
'54' :{'text': 'de Meurthe-et-Moselle', 'code': '54', 'url_d': '/wiki/Liste_des_monuments_historiques_de_Meurthe-et-Moselle', 'name': 'Meurthe-et-Moselle'},
'55' :{'text': 'de la Meuse', 'code': '55', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Meuse', 'name': 'Meuse'},
'56' :{'text': 'du Morbihan', 'code': '56', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Lorient", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Pontivy", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Vannes"], 'name': 'Morbihan'},
'57' :{'text': 'de la Moselle', 'code': '57', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Moselle', 'name': 'Moselle'},
'58' :{'text': 'de la Nièvre', 'code': '58', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Nièvre', 'name': 'Nièvre'},
'59' :{'text': 'du Nord', 'code': '59', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Nord_(A-L)', '/wiki/Liste_des_monuments_historiques_du_Nord_(M-Z)'], 'name': 'Nord'},
'60' :{'text': "de l'Oise", 'code': '60', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Oise_(ouest)", "/wiki/Liste_des_monuments_historiques_de_l'Oise_(est)"], 'name': 'Oise'},
'61' :{'text': "de l'Orne", 'code': '61', 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Orne", 'name': 'Orne'},
'62' :{'text': 'du Pas-de-Calais', 'code': '62', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Pas-de-Calais_(A-H)', '/wiki/Liste_des_monuments_historiques_du_Pas-de-Calais_(I-Z)'], 'name': 'Pas-de-Calais'},
'63' :{'text': 'du Puy-de-Dôme', 'code': '63', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Puy-de-Dôme_(A-L)', '/wiki/Liste_des_monuments_historiques_du_Puy-de-Dôme_(M-Z)'], 'name': 'Puy-de-Dôme'},
'64' :{'text': 'des Pyrénées-Atlantiques', 'code': '64', 'url_d': ['/wiki/Liste_des_monuments_historiques_des_Pyrénées-Atlantiques_(A-L)', '/wiki/Liste_des_monuments_historiques_des_Pyrénées-Atlantiques_(M-Z)'], 'name': 'Pyrénées-Atlantiques'},
'65' :{'text': 'des Hautes-Pyrénées', 'code': '65', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Hautes-Pyrénées', 'name': 'Hautes-Pyrénées'},
'66' :{'text': 'des Pyrénées-Orientales', 'code': '66', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Pyrénées-Orientales', 'name': 'Pyrénées-Orientales'},
'67' :{'text': 'du Bas-Rhin', 'code': '67', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Bas-Rhin_(A-L)', '/wiki/Liste_des_monuments_historiques_du_Bas-Rhin_(M-Z)'], 'name': 'Bas-Rhin'},
'68' :{'text': 'du Haut-Rhin', 'code': '68', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Haut-Rhin', 'name': 'Haut-Rhin'},
'69' :{'text': 'du Rhône', 'code': '69', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_Rhône', '/wiki/Liste_des_monuments_historiques_de_la_Métropole_de_Lyon'], 'name': 'Rhône'},
'70' :{'text': 'de la Haute-Saône', 'code': '70', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Haute-Saône_(Vesoul_-_Gray)', '/wiki/Liste_des_monuments_historiques_de_la_Haute-Saône_(Lure_-_Héricourt)', '/wiki/Liste_des_monuments_historiques_de_la_Haute-Saône_(Luxeuil_-_Jussey)'], 'name': 'Haute-Saône'},
'71' :{'text': 'de Saône-et-Loire', 'code': '71', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Saône-et-Loire_(A-L)', '/wiki/Liste_des_monuments_historiques_de_la_Saône-et-Loire_(M-Z)'], 'name': 'Saône-et-Loire'},
'72' :{'text': 'de la Sarthe', 'code': '72', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Mamers", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_du_Mans", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_la_Flèche"], 'name': 'Sarthe'},
'73' :{'text': 'de la Savoie', 'code': '73', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Savoie', 'name': 'Savoie'},
'74' :{'text': 'de la Haute-Savoie', 'code': '74', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Haute-Savoie', 'name': 'Haute-Savoie'},
'75' :{'text': 'de Paris', 'code': '75', 'url_d': ['/wiki/Liste_des_monuments_historiques_du_1er_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_2e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_3e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_4e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_5e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_6e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_7e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_8e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_9e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_10e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_11e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_12e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_13e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_14e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_15e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_16e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_17e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_18e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_19e_arrondissement_de_Paris', '/wiki/Liste_des_monuments_historiques_du_20e_arrondissement_de_Paris'], 'name': 'Paris'},
'76' :{'text': 'de la Seine-Maritime', 'code': '76', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Dieppe", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_du_Havre", "/wiki/Liste_des_monuments_historiques_de_l'arrondissement_de_Rouen"], 'name': 'Seine-Maritime'},
'77' :{'text': 'de Seine-et-Marne', 'code': '77', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Seine-Maritime_(ouest)', '/wiki/Liste_des_monuments_historiques_de_la_Seine-Maritime_(est)'], 'name': 'Seine-et-Marne'},
'78' :{'text': 'des Yvelines', 'code': '78', 'url_d': ['/wiki/Liste_des_monuments_historiques_des_Yvelines_(nord)', '/wiki/Liste_des_monuments_historiques_des_Yvelines_(sud)'], 'name': 'Yvelines'},
'79' :{'text': 'des Deux-Sèvres', 'code': '79', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Deux-Sèvres', 'name': 'Deux-Sèvres'},
'80' :{'text': 'de la Somme', 'code': '80', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Somme', 'name': 'Somme'},
'81' :{'text': 'du Tarn', 'code': '81', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Tarn', 'name': 'Tarn'},
'82' :{'text': 'de Tarn-et-Garonne', 'code': '82', 'url_d': '/wiki/Liste_des_monuments_historiques_de_Tarn-et-Garonne', 'name': 'Tarn-et-Garonne'},
'83' :{'text': 'du Var', 'code': '83', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Var', 'name': 'Var'},
'84' :{'text': 'de Vaucluse', 'code': '84', 'url_d': '/wiki/Liste_des_monuments_historiques_de_Vaucluse', 'name': 'Vaucluse'},
'85' :{'text': 'de la Vendée', 'code': '85', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Vendée', 'name': 'Vendée'},
'86' :{'text': 'de la Vienne', 'code': '86', 'url_d': ['/wiki/Liste_des_monuments_historiques_de_la_Vienne_(A-L)', '/wiki/Liste_des_monuments_historiques_de_la_Vienne_(M-Z)'], 'name': 'Vienne'},
'87' :{'text': 'de la Haute-Vienne', 'code': '87', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Haute-Vienne', 'name': 'Haute-Vienne'},
'88' :{'text': 'des Vosges', 'code': '88', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Vosges', 'name': 'Vosges'},
'89' :{'text': "de l'Yonne", 'code': '89', 'url_d': ["/wiki/Liste_des_monuments_historiques_de_l'Yonne_(A-M)", "/wiki/Liste_des_monuments_historiques_de_l'Yonne_(N-Z)"], 'name': 'Yonne'},
'90' :{'text': 'du Territoire de Belfort', 'code': '90', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Territoire_de_Belfort', 'name': 'Territoire de Belfort'},
'91' :{'text': "de l'Essonne", 'code': '91', 'url_d': "/wiki/Liste_des_monuments_historiques_de_l'Essonne", 'name': 'Essonne'},
'92' :{'text': 'des Hauts-de-Seine', 'code': '92', 'url_d': '/wiki/Liste_des_monuments_historiques_des_Hauts-de-Seine', 'name': 'Hauts-de-Seine'},
'93' :{'text': 'de la Seine-Saint-Denis', 'code': '93', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Seine-Saint-Denis', 'name': 'Seine-Saint-Denis'},
'94' :{'text': 'du Val-de-Marne', 'code': '94', 'url_d': '/wiki/Liste_des_monuments_historiques_du_Val-de-Marne', 'name': 'Val-de-Marne'},
'95' :{'text': "du Val-d'Oise", 'code': '95', 'url_d': "/wiki/Liste_des_monuments_historiques_du_Val-d'Oise", 'name': "Val-d'Oise"},
'971' :{'text': 'de la Guadeloupe', 'code': '971', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Guadeloupe', 'name': 'Guadeloupe'},
'972' :{'text': 'de la Martinique', 'code': '972', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Martinique', 'name': 'Martinique'},
'973' :{'text': 'de la Guyane', 'code': '973', 'url_d': '/wiki/Liste_des_monuments_historiques_de_la_Guyane', 'name': 'Guyane'},
'974' :{'text': 'de La Réunion', 'code': '974', 'url_d': '/wiki/Liste_des_monuments_historiques_de_La_Réunion', 'name': 'Réunion'},
'975' :{'text': 'de Saint-Pierre-et-Miquelon', 'code': '975', 'url_d': '/wiki/Liste_des_monuments_historiques_de_Saint-Pierre-et-Miquelon', 'name': 'Saint-Pierre-et-Miquelon'},
}