dic_dep = {'01' :{'code': '01', 'text': "de l'Ain", 'name': 'Ain', 'url': "de_l'Ain"},
'02' :{'code': '02', 'text': "de l'Aisne", 'name': 'Aisne', 'url': ["de_l'Aisne_(nord)", "de_l'Aisne_(sud)"]},
'03' :{'code': '03', 'text': "de l'Allier", 'name': 'Allier', 'url': ["de_l'Allier_(A-H)", "de_l'Allier_(I-Z)"]},
'04' :{'code': '04', 'text': 'des Alpes-de-Haute-Provence', 'name': 'Alpes-de-Haute-Provence', 'url': 'des_Alpes-de-Haute-Provence'},
'05' :{'code': '05', 'text': 'des Hautes-Alpes', 'name': 'Hautes-Alpes', 'url': 'des_Hautes-Alpes'},
'06' :{'code': '06', 'text': 'des Alpes-Maritimes', 'name': 'Alpes-Maritimes', 'url': 'des_Alpes-Maritimes'},
'07' :{'code': '07', 'text': "de l'Ardèche", 'name': 'Ardèche', 'url': "de_l'Ardèche"},
'08' :{'code': '08', 'text': 'des Ardennes', 'name': 'Ardennes', 'url': 'des_Ardennes'},
'09' :{'code': '09', 'text': "de l'Ariège", 'name': 'Ariège', 'url': "de_l'Ariège"},
'10' :{'code': '10', 'text': "de l'Aube", 'name': 'Aube', 'url': "de_l'Aube"},
'11' :{'code': '11', 'text': "de l'Aude", 'name': 'Aude', 'url': "de_l'Aude"},
'12' :{'code': '12', 'text': "de l'Aveyron", 'name': 'Aveyron', 'url': "de_l'Aveyron"},
'13' :{'code': '13', 'text': 'des Bouches-du-Rhône', 'name': 'Bouches-du-Rhône', 'url': 'des_Bouches-du-Rhône'},
'14' :{'code': '14', 'text': 'du Calvados', 'name': 'Calvados', 'url': ["de_l'arrondissement_de_Bayeux", "de_l'arrondissement_de_Caen", "de_l'arrondissement_de_Lisieux", "de_l'arrondissement_de_Vire"]},
'15' :{'code': '15', 'text': 'du Cantal', 'name': 'Cantal', 'url': 'du_Cantal'},
'16' :{'code': '16', 'text': 'de la Charente', 'name': 'Charente', 'url': 'de_la_Charente'},
'17' :{'code': '17', 'text': 'de la Charente-Maritime', 'name': 'Charente-Maritime', 'url': ['de_la_Charente-Maritime_(A-N)', 'de_la_Charente-Maritime_(O-Z)']},
'18' :{'code': '18', 'text': 'du Cher', 'name': 'Cher', 'url': 'du_Cher'},
'19' :{'code': '19', 'text': 'de la Corrèze', 'name': 'Corrèze', 'url': 'de_la_Corrèze'},
'2A' :{'code': '2A', 'text': 'de la Corse-du-Sud', 'name': 'Corse-du-Sud', 'url': 'de_la_Corse-du-Sud'},
'2B' :{'code': '2B', 'text': 'de la Haute-Corse', 'name': 'Haute-Corse', 'url': 'de_la_Haute-Corse'},
'21' :{'code': '21', 'text': "de la Côte-d'Or", 'name': "Côte-d'Or", 'url': ["de_la_Côte-d'Or_(A-L)", "de_la_Côte-d'Or_(M-Z)"]},
'22' :{'code': '22', 'text': "des Côtes-d'Armor", 'name': "Côtes-d'Armor", 'url': ["des_Côtes-d'Armor_(A-O)", "des_Côtes-d'Armor_(P-Z)"]},
'23' :{'code': '23', 'text': 'de la Creuse', 'name': 'Creuse', 'url': 'de_la_Creuse'},
'24' :{'code': '24', 'text': 'de la Dordogne', 'name': 'Dordogne', 'url': ["de_l'arrondissement_de_Bergerac", "de_l'arrondissement_de_Nontron", "de_l'arrondissement_de_Périgueux", "de_l'arrondissement_de_Sarlat-la-Canéda"]},
'25' :{'code': '25', 'text': 'du Doubs', 'name': 'Doubs', 'url': 'du_Doubs'},
'26' :{'code': '26', 'text': 'de la Drôme', 'name': 'Drôme', 'url': 'de_la_Drôme'},
'27' :{'code': '27', 'text': "de l'Eure", 'name': 'Eure', 'url': ["de_l'Eure_(A-I)", "de_l'Eure_(J-Z)"]},
'28' :{'code': '28', 'text': "d'Eure-et-Loir", 'name': 'Eure-et-Loir', 'url': "d'Eure-et-Loir"},
'29' :{'code': '29', 'text': 'du Finistère', 'name': 'Finistère', 'url': ['du_Finistère_(A-O)', 'du_Finistère_(P-Z)']},
'30' :{'code': '30', 'text': 'du Gard', 'name': 'Gard', 'url': 'du_Gard'},
'31' :{'code': '31', 'text': 'de la Haute-Garonne', 'name': 'Haute-Garonne', 'url': ['de_la_Haute_Garonne_(A-L)', 'de_la_Haute_Garonne_(M-Z)']},
'32' :{'code': '32', 'text': 'du Gers', 'name': 'Gers', 'url': 'du_Gers'},
'33' :{'code': '33', 'text': 'de la Gironde', 'name': 'Gironde', 'url': ["de_l'arrondissement_de_Arcachon", "de_l'arrondissement_de_Blaye", "de_l'arrondissement_de_Bordeaux", "de_l'arrondissement_de_Langon", "de_l'arrondissement_de_Lesparre-Médoc", "de_l'arrondissement_de_Libourne"]},
'34' :{'code': '34', 'text': "de l'Hérault", 'name': 'Hérault', 'url': ["de_l'Eure_(A-I)", "de_l'Eure_(J-Z)"]},
'35' :{'code': '35', 'text': "d'Ille-et-Vilaine", 'name': 'Ille-et-Vilaine', 'url': "d'Ille-et-Vilaine"},
'36' :{'code': '36', 'text': "de l'Indre", 'name': 'Indre', 'url': "de_l'Indre"},
'37' :{'code': '37', 'text': "d'Indre-et-Loire", 'name': 'Indre-et-Loire', 'url': ["d'Indre-et-Loire_(A-J)", "d'Indre-et-Loire_(K-Z)"]},
'38' :{'code': '38', 'text': "de l'Isère", 'name': 'Isère', 'url': "de_l'Isère"},
'39' :{'code': '39', 'text': 'du département du Jura', 'name': 'Jura', 'url': 'du_département_du_Jura'},
'40' :{'code': '40', 'text': 'des Landes', 'name': 'Landes', 'url': 'des_Landes'},
'41' :{'code': '41', 'text': 'de Loir-et-Cher', 'name': 'Loir-et-Cher', 'url': 'de_Loir-et-Cher'},
'42' :{'code': '42', 'text': 'de la Loire', 'name': 'Loire', 'url': 'de_la_Loire'},
'43' :{'code': '43', 'text': 'de la Haute-Loire', 'name': 'Haute-Loire', 'url': ['de_la_Haute_Loire_(ouest)', 'de_la_Haute_Loire_(est)']},
'44' :{'code': '44', 'text': 'de la Loire-Atlantique', 'name': 'Loire-Atlantique', 'url': 'de_la_Loire-Atlantique'},
'45' :{'code': '45', 'text': 'du Loiret', 'name': 'Loiret', 'url': 'du_Loiret'},
'46' :{'code': '46', 'text': 'du Lot', 'name': 'Lot', 'url': ['du_Lot_(A-K)', 'du_Lot_(L-Z)']},
'47' :{'code': '47', 'text': 'de Lot-et-Garonne', 'name': 'Lot-et-Garonne', 'url': ['du_Lot-et-Garonne_(A-L)', 'du_Lot-et-Garonne_(M-Z)']},
'48' :{'code': '48', 'text': 'de la Lozère', 'name': 'Lozère', 'url': 'de_la_Lozère'},
'49' :{'code': '49', 'text': 'de Maine-et-Loire', 'name': 'Maine-et-Loire', 'url': ['du_Maine-et-Loire_(nord)', 'du_Maine-et-Loire_(sud)']},
'50' :{'code': '50', 'text': 'de la Manche', 'name': 'Manche', 'url': 'de_la_Manche'},
'51' :{'code': '51', 'text': 'de la Marne', 'name': 'Marne', 'url': 'de_la_Marne'},
'52' :{'code': '52', 'text': 'de la Haute-Marne', 'name': 'Haute-Marne', 'url': 'de_la_Haute-Marne'},
'53' :{'code': '53', 'text': 'de la Mayenne', 'name': 'Mayenne', 'url': 'de_la_Mayenne'},
'54' :{'code': '54', 'text': 'de Meurthe-et-Moselle', 'name': 'Meurthe-et-Moselle', 'url': 'de_Meurthe-et-Moselle'},
'55' :{'code': '55', 'text': 'de la Meuse', 'name': 'Meuse', 'url': 'de_la_Meuse'},
'56' :{'code': '56', 'text': 'du Morbihan', 'name': 'Morbihan', 'url': ["de_l'arrondissement_de_Lorient", "de_l'arrondissement_de_Pontivy", "de_l'arrondissement_de_Vannes"]},
'57' :{'code': '57', 'text': 'de la Moselle', 'name': 'Moselle', 'url': 'de_la_Moselle'},
'58' :{'code': '58', 'text': 'de la Nièvre', 'name': 'Nièvre', 'url': 'de_la_Nièvre'},
'59' :{'code': '59', 'text': 'du Nord', 'name': 'Nord', 'url': ['du_Nord_(A-L)', 'du_Nord_(M-Z)']},
'60' :{'code': '60', 'text': "de l'Oise", 'name': 'Oise', 'url': ["de_l'Oise_(ouest)", "de_l'Oise_(est)"]},
'61' :{'code': '61', 'text': "de l'Orne", 'name': 'Orne', 'url': "de_l'Orne"},
'62' :{'code': '62', 'text': 'du Pas-de-Calais', 'name': 'Pas-de-Calais', 'url': ['du_Pas-de-Calais_(A-H)', 'du_Pas-de-Calais_(I-Z)']},
'63' :{'code': '63', 'text': 'du Puy-de-Dôme', 'name': 'Puy-de-Dôme', 'url': ['du_Puy-de-Dôme_(A-L)', 'du_Puy-de-Dôme_(M-Z)']},
'64' :{'code': '64', 'text': 'des Pyrénées-Atlantiques', 'name': 'Pyrénées-Atlantiques', 'url': ['des_Pyrénées-Atlantiques_(A-L)', 'des_Pyrénées-Atlantiques_(M-Z)']},
'65' :{'code': '65', 'text': 'des Hautes-Pyrénées', 'name': 'Hautes-Pyrénées', 'url': 'des_Hautes-Pyrénées'},
'66' :{'code': '66', 'text': 'des Pyrénées-Orientales', 'name': 'Pyrénées-Orientales', 'url': 'des_Pyrénées-Orientales'},
'67' :{'code': '67', 'text': 'du Bas-Rhin', 'name': 'Bas-Rhin', 'url': ['du_Bas-Rhin_(A-L)', 'du_Bas-Rhin_(M-Z)']},
'68' :{'code': '68', 'text': 'du Haut-Rhin', 'name': 'Haut-Rhin', 'url': 'du_Haut-Rhin'},
'69' :{'code': '69', 'text': 'du Rhône', 'name': 'Rhône', 'url': ['du_Rhône', 'de_la_Métropole_de_Lyon']},
'70' :{'code': '70', 'text': 'de la Haute-Saône', 'name': 'Haute-Saône', 'url': ['de_la_Haute-Saône_(Vesoul_-_Gray)', 'de_la_Haute-Saône_(Lure_-_Héricourt)', 'de_la_Haute-Saône_(Luxeuil_-_Jussey)']},
'71' :{'code': '71', 'text': 'de Saône-et-Loire', 'name': 'Saône-et-Loire', 'url': ['de_la_Saône-et-Loire_(A-L)', 'de_la_Saône-et-Loire_(M-Z)']},
'72' :{'code': '72', 'text': 'de la Sarthe', 'name': 'Sarthe', 'url': ["de_l'arrondissement_de_Mamers", "de_l'arrondissement_du_Mans", "de_l'arrondissement_de_la_Flèche"]},
'73' :{'code': '73', 'text': 'de la Savoie', 'name': 'Savoie', 'url': 'de_la_Savoie'},
'74' :{'code': '74', 'text': 'de la Haute-Savoie', 'name': 'Haute-Savoie', 'url': 'de_la_Haute-Savoie'},
'75' :{'code': '75', 'text': 'de Paris', 'name': 'Paris', 'url': ['du_1er_arrondissement_de_Paris', 'du_2e_arrondissement_de_Paris', 'du_3e_arrondissement_de_Paris', 'du_4e_arrondissement_de_Paris', 'du_5e_arrondissement_de_Paris', 'du_6e_arrondissement_de_Paris', 'du_7e_arrondissement_de_Paris', 'du_8e_arrondissement_de_Paris', 'du_9e_arrondissement_de_Paris', 'du_10e_arrondissement_de_Paris', 'du_11e_arrondissement_de_Paris', 'du_12e_arrondissement_de_Paris', 'du_13e_arrondissement_de_Paris', 'du_14e_arrondissement_de_Paris', 'du_15e_arrondissement_de_Paris', 'du_16e_arrondissement_de_Paris', 'du_17e_arrondissement_de_Paris', 'du_18e_arrondissement_de_Paris', 'du_19e_arrondissement_de_Paris', 'du_20e_arrondissement_de_Paris']},
'76' :{'code': '76', 'text': 'de la Seine-Maritime', 'name': 'Seine-Maritime', 'url': ["de_l'arrondissement_de_Dieppe", "de_l'arrondissement_du_Havre", "de_l'arrondissement_de_Rouen"]},
'77' :{'code': '77', 'text': 'de Seine-et-Marne', 'name': 'Seine-et-Marne', 'url': ['de_la_Seine-Maritime_(ouest)', 'de_la_Seine-Maritime_(est)']},
'78' :{'code': '78', 'text': 'des Yvelines', 'name': 'Yvelines', 'url': ['des_Yvelines_(nord)', 'des_Yvelines_(sud)']},
'79' :{'code': '79', 'text': 'des Deux-Sèvres', 'name': 'Deux-Sèvres', 'url': 'des_Deux-Sèvres'},
'80' :{'code': '80', 'text': 'de la Somme', 'name': 'Somme', 'url': 'de_la_Somme'},
'81' :{'code': '81', 'text': 'du Tarn', 'name': 'Tarn', 'url': 'du_Tarn'},
'82' :{'code': '82', 'text': 'de Tarn-et-Garonne', 'name': 'Tarn-et-Garonne', 'url': 'de_Tarn-et-Garonne'},
'83' :{'code': '83', 'text': 'du Var', 'name': 'Var', 'url': 'du_Var'},
'84' :{'code': '84', 'text': 'de Vaucluse', 'name': 'Vaucluse', 'url': 'de_Vaucluse'},
'85' :{'code': '85', 'text': 'de la Vendée', 'name': 'Vendée', 'url': 'de_la_Vendée'},
'86' :{'code': '86', 'text': 'de la Vienne', 'name': 'Vienne', 'url': ['de_la_Vienne_(A-L)', 'de_la_Vienne_(M-Z)']},
'87' :{'code': '87', 'text': 'de la Haute-Vienne', 'name': 'Haute-Vienne', 'url': 'de_la_Haute-Vienne'},
'88' :{'code': '88', 'text': 'des Vosges', 'name': 'Vosges', 'url': 'des_Vosges'},
'89' :{'code': '89', 'text': "de l'Yonne", 'name': 'Yonne', 'url': ["de_l'Yonne_(A-M)", "de_l'Yonne_(N-Z)"]},
'90' :{'code': '90', 'text': 'du Territoire de Belfort', 'name': 'Territoire de Belfort', 'url': 'du_Territoire_de_Belfort'},
'91' :{'code': '91', 'text': "de l'Essonne", 'name': 'Essonne', 'url': "de_l'Essonne"},
'92' :{'code': '92', 'text': 'des Hauts-de-Seine', 'name': 'Hauts-de-Seine', 'url': 'des_Hauts-de-Seine'},
'93' :{'code': '93', 'text': 'de la Seine-Saint-Denis', 'name': 'Seine-Saint-Denis', 'url': 'de_la_Seine-Saint-Denis'},
'94' :{'code': '94', 'text': 'du Val-de-Marne', 'name': 'Val-de-Marne', 'url': 'du_Val-de-Marne'},
'95' :{'code': '95', 'text': "du Val-d'Oise", 'name': "Val-d'Oise", 'url': "du_Val-d'Oise"},
'971' :{'code': '971', 'text': 'de la Guadeloupe', 'name': 'Guadeloupe', 'url': 'de_la_Guadeloupe'},
'972' :{'code': '972', 'text': 'de la Martinique', 'name': 'Martinique', 'url': 'de_la_Martinique'},
'973' :{'code': '973', 'text': 'de la Guyane', 'name': 'Guyane', 'url': 'de_la_Guyane'},
'974' :{'code': '974', 'text': 'de La Réunion', 'name': 'Réunion', 'url': 'de_La_Réunion'},
'975' :{'code': '975', 'text': 'de Saint-Pierre-et-Miquelon', 'name': 'Saint-Pierre-et-Miquelon', 'url': 'de_Saint-Pierre-et-Miquelon'},
}